---

- hosts: all
  become: yes
  pre_tasks:

  - name: update install (Rocky Linux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"
  
  - name: update install (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
